listening-port=3478
min-port=49152
max-port=50151
listening-ip=0.0.0.0
relay-ip=0.0.0.0
fingerprint
lt-cred-mech
use-auth-secret
realm=roundtalk.shamilfrontend.ru
server-name=roundtalk.shamilfrontend.ru
no-cli
no-tls
no-dtls
no-software-attribute
simple-log
